name: platescape
description: "Where every plate tells a story."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_local_notifications: ^18.0.1
  flutter_timezone: ^4.1.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  shared_preferences: ^2.5.2
  sqflite: ^2.4.2
  timezone: ^0.10.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  test: ^1.25.15

flutter:
  uses-material-design: true

  assets:
    - assets/
